package com.food.fooddeliverybackend.enums;

public enum Amenities {
    BREAKFAST,
    HOME_DELIVERY,
    TAKEAWAY_AVAILABLE,
    OUTDOOR_SEATING,
    INDOOR_SEATING,
    ROMANTIC_DATING,
    TAKE_BOOKING_RECOMMENDED,
    PARKING_AVAILABLE,
    FREE_WIFI,
    AIR_CONDITIONING,
    PET_FRIENDLY,
    KIDS_FRIENDLY,
    LIVE_MUSIC,
    BAR_AVAILABLE,
    VEGETARIAN_OPTIONS,
    NON_VEGETARIAN_OPTIONS,
    VEGAN_OPTIONS,
    WHEELCHAIR_ACCESSIBLE,
    CARD_PAYMENT,
    CASH_PAYMENT,
    FAMILY_SEATING,
    PRIVATE_DINING,
    BUFFET_AVAILABLE,
    SMOKING_AREA,
    TV_AVAILABLE,
    VALET_PARKING
}

